enwikipedia-acc/waca

.travis.yml, sql/create_db.sh, tests/bootstrap.php
As long as the pull request build passes, I'll just merge this myself.
=> Fix Travis builds

includes/DataObjects/CommunityUser.php, includes/DataObjects/User.php
=> Grant CheckUser based on 'checkuser' userright

includes/DataObject.php, includes/DataObjects/Comment.php, includes/Helpers/Logger.php
@stwalkerster requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/enwikipedia-acc/waca/
=> Scrutinizer Auto-Fixes

includes/DataObjects/CommunityUser.php, includes/DataObjects/User.php, includes/statistics/StatsIdUsers.php, includes/statistics/StatsUsers.php, sql/patches/patch08-rename-checkuser.sql, users.php
@stwalkerster Tested on local, could do with a test on dev as it is a database change.
=> phase out checkuser table and rename to root

sql/patches/patch12-requestcomment.sql
Awaiting confirmation that 3000 chars is ok - this is for issue #209
=> Patch to fix #209

includes/DataObjects/CommunityUser.php, includes/DataObjects/User.php
Alternate fix for enwikipedia-acc/waca#221
=> Check that an account is OAuth linked before querying permissions

includes/Validation/RequestValidationHelper.php, includes/statistics/StatsMain.php
Finishes fixing #215 
We should probably have a config option for this, but since @stwalkerster is currently on rewriting the config system, I'll leave that to him.  :P
=> When auto-deferring requests, send them to the new queue

team.php
I figure I'm allowed to do that now!
=> Adding my name

.gitignore, acc.php, templates/zoom-parts/request-actions.tpl
Fixed in the same way as the other two you fixed :smile:
=> Close another XSS hole

templates/header-internal.tpl
Addition of mailing list and standardize capitalization to dropdown menu
=> Dropdown menu; + mailing list

acc.php, functions.php, templates/mainpage/mainpage.tpl, templates/mainpage/requestlist.tpl
Couple of basic improvements to miser mode considering the current state of play in production
* Change the colour of the badge in miser mode
* Add list all button for those who are insane enough to click it. See commit message for more info.
=> Miser mode enhancements

redir.php, templates/zoom-parts/ip-links.tpl
We still need a better way of doing this.
=> #268 Add additional whois provider

search.php, templates/search/searchform.tpl
Now identified to Wikimedia Foundation.  This should be unlocked for certain research purposes.
=> Unlock IP Search for users

PrecacheGeolocation.php
Adds a new maintenance script which looks at all IP addresses in the
database and fetches the geolocation data for them all.
This will need to be scheduled via cron to have the desired effect, and
should be considered a quick-fix, not a long-term solution
Fixes #430 for master
=> Geolocation pre-caching

config.inc.php, includes/PdoDatabase.php
... until we sort out all the collation/charset issues
This is related to #25
=> Fix IRC notification issue with a really hacky fix

templates/welcometemplate/view.tpl
Use relative path to link to acc.php, fix #459 ?
=> Add curly brace to $baseurl var

acc.php, config.inc.php, functions.php, includes/DataObjects/CommunityUser.php, includes/DataObjects/User.php, includes/statistics/StatsIdUsers.php
Adds a minimum and current policy version for identification signatures
=> Change identification field to support versioning

redir.php, templates/zoom-parts/ip-links.tpl
=> Add IP Check tool

templates/zoom-parts/ip-links.tpl
=> Add LW CU tools for stews

templates/request/request-form.tpl
Previously linked to UserLogin special page, which does not have the form for resetting passwords
=> Link to PasswordReset for resetting the password

resources/styles.css, templates/welcome-template/list.tpl
Apparently I overcomplicated it. It would be good to just have a checkbox to tell if it is enabled and uncheck it to disable the feature. #261
=> Always show disable automatic welcoming button

acc.php, config.inc.php, templates/footer.tpl, templates/header-external.tpl, templates/header-internal.tpl, templates/registration/registerdisabled.tpl
Also adds ability to disable tool signup
=> Disable JS when not logged in

includes/ConsoleTasks/RegenerateStylesheetsTask.php, includes/DataObjects/CommunityUser.php, includes/DataObjects/User.php, includes/Pages/UserAuth/PagePreferences.php, includes/SiteConfiguration.php, resources/scss/bootstrap-alt.scss, sql/patches/patch31-darkmode.sql, templates/base.tpl, templates/preferences/prefs.tpl
Add an **experimental** alternate skin for the tool.
- Yes, this is an early prototype.
- Yes, there are some things which are hard-to-read.
- Yes, this is going to change massively in the future
- Yes, it's "good enough" to go to prod - there's no stability
problems etc that I'm aware of, it's just harder to read than
the light mode.
- No, I'm not going to accept any bug reports for it at the moment.
=> Dark mode when?

templates/zoom-parts/ip-links.tpl
Adding ":en:" to LWCU link to prevent red link on the log
=> Adding ":en:" to LWCU link

includes/ConsoleTasks/RefreshOAuthDataTask.php, includes/Helpers/Interfaces/IOAuthProtocolHelper.php, includes/Helpers/OAuthUserHelper.php, includes/Pages/PageWelcomeTemplateManagement.php, templates/preferences/prefs.tpl, templates/welcome-template/list.tpl
Fixes some minor issues detected in the newinternal go-live
=> Minor bugsquish

.travis.yml, tests/includes/IdentificationVerifierTest.php
Note: This will fail!  It does not fix the tests or the code, only enables them to be run.  I will follow up with test-fixing pull requests in the future.
=> Change to using the vendor phpunit, as that runs all tests.

templates/navigation-menu.tpl
Implement changes from #577 into navigation so appropriate items open in external window.
=> Enhance Navigation

resources/scss/bootstrap-alt.scss
Instead of forcing black to be white and white to be black, actually set the relevant variables to more sensible colours.
This will **still** need tweaking, but I think it's probably _mostly_ usable now.
=> Re-do dark skin from the ground up

includes/Pages/PageEditComment.php
When the request is posted, only handle it if it doesn't match the old comment text (comparison via !== between strings).
Closes #608
=> PageEditComment: Handle saving with no changes

templates/view-request/ip-links.tpl
Stewards will be able to adjust active global blocks this way if necessary without any extra clicks
=> change IPActiveGlobalBlock to meta link from en

includes/DataObjects/EmailTemplate.php, includes/Pages/RequestAction/PageCustomClose.php, resources/scss/_common.scss, resources/scss/_sortableTables.scss, resources/scss/bootstrap-alt.scss, templates/base.tpl
Several minor fixes:
* Changes to the dark mode hover styling for header rows on sortable tables to better fit in with the dark theme
* Add a HTML title on custom closes
=> Minor fixes

templates/statistics/top-creators-table.tpl, templates/statistics/top-creators.tpl
Also reinstate the highlight of the current user
Fixes #539
=> Bin the admin markings on TopCreators

includes/Pages/Request/PageRequestAccount.php
=> Strip leading/trailing spaces from requested usernames

includes/Helpers/IrcNotificationHelper.php
Private ban reasons were echoed to IRC
=> Fix information disclosure vulnerability

includes/Pages/PageEmailManagement.php, templates/email-management/edit.tpl
=> Add some protection against null JS questions on email templates

includes/Fragments/RequestData.php, includes/Fragments/RequestListData.php
=> Don't flag purged email addresses as "uncommon"

resources/global.js, templates/navigation-menu.tpl
=> Add option to re-show the site notice once it has been dismissed.

includes/Helpers/LogHelper.php, templates/logs/form.tpl
=> Minor log tidyup for log actions, and safety checks for missing objects

includes/Pages/RequestAction/PageCloseRequest.php, includes/Validation/RequestValidationHelper.php, includes/Validation/ValidationError.php, templates/view-request/username-section.tpl
Resolves #671, resolves #624, resolves #619.
First time sending a PR in to here and I'm not the neatest coder, please go easy :)
=> Add Global Username List, Check If Username is IP, Don't Email If Purged

includes/Helpers/SearchHelpers/JobQueueSearchHelper.php, includes/Helpers/SearchHelpers/SearchHelperBase.php, includes/Pages/PageJobQueue.php, templates/jobqueue/all.tpl, templates/pager.tpl
Resolves #680 + the bonus points!
=> Show job queue newest first

team.json
=> Update Amanda's entry and add me

includes/Helpers/SearchHelpers/JobQueueSearchHelper.php, includes/Pages/PageJobQueue.php, includes/Pages/PageViewRequest.php, includes/Security/RoleConfiguration.php, templates/view-request/main.tpl, templates/view-request/request-status-buttons.tpl
Disable reset request button after purge, unless admin. Remove 'Create Account' section from a closed request as it's pointless.
Resolves #617
=> UX Changes

includes/API/Actions/CountAction.php, includes/API/Actions/JsUsersAction.php, includes/ConsoleTasks/ClearOAuthDataTask.php, includes/DataObjects/Request.php, includes/Fragments/RequestData.php, includes/Helpers/LogHelper.php, includes/Pages/PageLog.php, includes/Pages/PageUserManagement.php, includes/Pages/PageViewRequest.php, includes/Pages/PageWelcomeTemplateManagement.php, includes/Pages/RequestAction/PageCloseRequest.php, includes/Pages/Statistics/StatsUsers.php, includes/Tasks/JsonApiPageBase.php, includes/Tasks/PageBase.php
Look likes I missed these the first time round... heh
=> More scrutinizer "patches"

templates/login/otp.tpl
It is a bit annoying to type your TOTP token just to find out that you actually wrote nothing :-)
See also [T229757](https://phabricator.wikimedia.org/T229757)
=> otp: Autofocus text cursor on TOTP field

includes/ExceptionHandler.php, includes/Helpers/HttpHelper.php, includes/Helpers/IrcNotificationHelper.php, includes/Pages/PageEditComment.php, includes/Pages/PageErrorLogViewer.php, includes/Validation/RequestValidationHelper.php, templates/edit-comment.tpl, templates/errorlog/details.tpl, templates/errorlog/main.tpl
Various fixes for unhandled exceptions and improvements to error logging for detection of other problems.
=> Exception fixes

includes/Pages/RequestAction/PageCloseRequest.php, includes/Pages/RequestAction/PageCustomClose.php, templates/custom-close.tpl
=> Add account existence check to manual-creation custom closes

includes/PdoDatabase.php
=> Default to using READ COMMITTED transactions

includes/Security/SecurityManager.php
**This touches core security code**
Currently, user role and identification lookups are done every single time we do an ACL check on the tool. For most pages, this happens about twenty times per request, which is about forty database queries.
This change caches this information on a per-request basis, such that lookups done *within the same request* come from the cache, causing the database lookups to be done once per request, not once per ACL check.
The cache is split by user, for instances where we need to check another account's ACLs (which is rare!). The only instance of this that comes to mind is preference editing from within user management - we check the target user's ACL to display whether or not a user is authorised to use OAuth/bot creation. As such, the cache splitting can be …
=> Cache role & identification lookups within the current request context

templates/view-request/related-requests.tpl
=> Fix unhandled exception caused by hospital queue related requests.

config.inc.php, includes/SiteConfiguration.php
Remove some deprecated code which is not being used anymore.
=> Remove deprecated code

includes/Helpers/BlacklistHelper.php, includes/WebStart.php
Replacement PR for #744 as I Git branch failed...
Also fix #737
=> Fix Title Blacklist display + add failure logging

redir.php, templates/view-request/ip-links.tpl
Add link to IPalyzer which looks very useful! - Example: https://ipalyzer.com/135.181.165.222 (IP is my own server at Hetzner, not linked to any request)
=> Add IPalyzer

includes/Helpers/LogHelper.php, includes/Helpers/Logger.php, includes/Pages/PageViewRequest.php, includes/Pages/RequestAction/PageManuallyConfirm.php, includes/Router/RequestRouter.php, includes/Security/RoleConfiguration.php, templates/view-request/not-confirmed.tpl
Same as #753 , this time will less GitHub weirdness.
=> Manual confirm 259

templates/view-request/antispoof-results.tpl
Update the antispoof centralauth check as well
=> Point antispoof centralauth check to meta (#758)

config.inc.php, includes/SiteConfiguration.php, redir.php
switched http to https in config.inc.php , SiteConfiguration.php  and redir.php's domain mode
=> switched http to https in config.inc.php , SiteConfiguration.php  and redir.php's domain mode

includes/Providers/IpLocationProvider.php
fixes #761 
added https in IpLocationProvider.php
=> added https in IpLocationProvider.php ( line no 125 ) issue fixes #761

includes/Fragments/RequestData.php, templates/view-request/main.tpl
Add a check to see if request is in the hospital queue and prevent auto-(re)creation if so, as it doesn't make sense to offer it when it failed during that exact process.
Also, clean up the code so there are not 5 of the same divs in the code. Also, I'm sure the 2 extra 'createOauth' ids should be 'createBot'
=> Hospital Check + Cleanup

redir.php, templates/view-request/ip-links.tpl
This requests adds Spur to the check links which can provide preliminary (not definitive) proxy data to help guide reviews on proxies.
=> Add Spur to Check Links

templates/request/request-form.tpl
Per https://phabricator.wikimedia.org/T254045
=> Add = to banned username chars

INSTALLING.md, docker-compose.yml
Prod is now on MariaDB 10.11.3.
=> Bump docker + documentation versions for prod upgrade

config.inc.php, includes/ConsoleTasks/ClearOldDataTask.php, includes/DataObjects/RequestData.php, includes/Fragments/RequestData.php, includes/Pages/Request/PageEmailConfirmationRequired.php, includes/Pages/Request/PageRequestAccount.php, includes/Pages/Request/PageRequestSubmitted.php, includes/SiteConfiguration.php, includes/WebRequest.php, resources/scss/_viewRequest.scss, sql/patches/patch44-client-hints.sql, templates/view-request/main-with-checkuser-data.tpl
=> Implement Clint Hints

includes/Fragments/TemplateOutput.php, templates/base.tpl
Regression from preferences refactor
=> Change skin default back to 'auto'

includes/SiteConfiguration.php, sql/patches/patch46-antispoof-cache.sql
=> Bump antispoofcache to 512 chars

config.inc.php, includes/ExceptionHandler.php, includes/Helpers/BlacklistHelper.php, includes/Pages/Registration/PageRegisterBase.php, includes/Pages/UserAuth/PageChangePassword.php, includes/Pages/UserAuth/PageForgotPassword.php, includes/Validation/RequestValidationHelper.php, includes/WebStart.php, templates/forgot-password/forgotpwreset.tpl, templates/preferences/changePassword.tpl, templates/registration/register.tpl, tests/includes/Helpers/BlacklistHelperTest.php
Changes both to how the global exception handler does logging, fixes for exceptions that were reaching the global exception handler, and reducing the amount of AntiSpoof noise that gets logged
=> Various exception handling tweaks

includes/Pages/PageEmailManagement.php
=> Fix editing of default email template

includes/Pages/RequestAction/PageCloseRequest.php, templates/close-confirmations/account-created.tpl, templates/close-confirmations/email-sent.tpl
I believe these will resolve #877 per comments from stw
The third, checkReserveProtect, doesn't need adjusting as it doesn't use showConfirmation
=> Add skipAutoWelcome to resolve #877

includes/Helpers/IrcNotificationHelper.php
(I assume that's what happened at 8:09 PM Eastern today in IRC, among other times)
=> Fix bug where checkuser-only comments were treated as visible to all users in IRC

redir.php
=> update Spur link

tests/includes/IdentificationVerifierTest.php
One test case was changed per https://meta.wikimedia.org/w/index.php?title=Access_to_nonpublic_personal_data_policy/Noticeboard&diff=prev&oldid=27702669
=> Fix unit tests

includes/API/Actions/MetricsAction.php, includes/Router/ApiRequestRouter.php, includes/Tasks/TextApiPageBase.php
This should replace the script at https://accounts-dev.wmflabs.org/other/prometheus.php which was parsing the result of the status API and re-writing it into the metrics format.
=> Add metrics API endpoint

templates/view-request/createbuttons/manual.tpl
=> Sul3 quickfix

includes/SiteConfiguration.php, sql/patches/patch51-useragent-nullable.sql
=> Allow UA to be NULL

includes/Fragments/RequestData.php, redir.php, smarty-plugins/modifier.cidr.php, templates/view-request/ip-links.tpl, templates/view-request/ip-section.tpl, tests/bootstrap.php, tests/smarty-plugins/CidrTests.php
=> Clean up breakage in some tools caused by IPv6
