templates/zoom-parts/username-section.tpl
The "Note: This account has already been created" message should work
properly again, and a password reset button has been added to it.
=> Fix issue #162.

.scrutinizer.yml
This is a fix for #237, however please note that no code inspections are run of the tests directory at all.
=> Ignore tests subdirectory from inspections

acc.php
This should partially fix #250 for the legacy code. This will not fix the issue for custom closes, that's going to be a lot more challenging, but this should fix the initially reported problem.
=> Look up default action for close reason for created check

acc.php
With this patch, the tool will no longer throw PHP fatal errors when a request
is dropped.
=> Fix for breaking bug in rel6.8.9

templates/zoom-parts/request-actions.tpl
Adjust the generated URL to create accounts on Wikipedia to match the presumed
changes made by AuthManager.  This will allow the email and reason fields on the
account creation form to be prefilled by the tool again.
Problem with the ACC tool no longer pre-populating the email and reason fields on Wikipedia's create account form reported originally on IRC by JJMC89.  This fix tested to work as expected on my local vagrant instance of ACC with the actual Wikipedia.
This pull is based off master, not newinternal, and I plan to create rel6.8.11 on merge of this pull request, with a corresponding deploy to production.
Sorry in advance @stwalkerster for giving you another code review, and for another thing to foreport into newinternal.  :P
=> Adjust account create URL for AuthManager? changes

ClearOldData.php
This has the effect of ensuring that requests have their data preserved for as
long as they are open.  With this patch, closed requests will have their data
cleared once they become older than 14 days; if a request has been open for
longer than 14 days, that request's private data will be purged "immediately"
upon close - more specifically, on the next run of the dataclear script after
the request is closed.
We may wish to modify this so that requests' private data is purged 14 days
after the request is closed, whenever that is, regardless of how old the
request was when it was closed.  This would be, of course, pending WMF approval,
and I'll also port this patch to newinternal once we've finalized the approach
to take.
=> Alter dataclear script to only purge closed reqs

includes/DataObjects/User.php
Analysing some XHProf data has revealed that the `User::isCheckuser` function is exceedingly slow.
The old implementation of `return $this->checkuser == 1 || $this->oauthCanCheckUser()` means that the OAuth identity ticket will be checked on every call of this method, which involves an unserialize, date cache check, array search, and a possible remote fetch. 
Needless to say, this is something which we don't care if it changes within a request, so caching this is appropriate.
This, unfortunately, isn't really possible for me to test locally.
=> Performance: cache the checkuser status of a user

templates/header-internal.tpl
- Freenode serves webchat over HTTPS, so I think we should take advantage of that.
- My editor removed trailing whitespace in this file. Let me know if you want me to revert those lines.
=> Make the webchat link in the header be HTTPS

redir.php
An issue reported by DatGuy on IRC, where a username request for Foo&Bar
was getting passed to Google as /search?q=Foo&Bar instead of
/search?q=Foo%26Bar - this is caused by us using htmlentities instead of
urlencoding. We're now additionally using json_encode to create the
javascript string instead of manually wrapping the search term in quotes
to prevent escaping the string.
=> Fix encoding issue in redirection tool

redir.php, templates/zoom-parts/ip-links.tpl
Adds a link to project honeypot to the IP links section; useful for determining patterns of abusive IPs and when requests may need more scrutiny.
=> Add Link to Project Honeypot

redir.php
Due to technical difficulties, we can miss some important notabilities based on little things like spaces when searching for an exact string.  Reversing this to ensure we don't miss potential results that are relevant.
=> Remove surrounding quotes in Google Search

acc.php, functions.php, oauth/callback.php, search.php, statistics.php, team.php, users.php
Makes profiler output more clear as to which opcode-cached things are caused by the session.
Related to #421
=> Wrap session start in new function

ClearOldData.php, index.php
=> Move Request::cleanExpiredUnconfirmedRequests to maintenance script

redir.php, templates/zoom-parts/ip-links.tpl
This commit swaps the WHOIS tools presented in the IP address information section, such that the primary WHOIS tool is now the WMF ToolForge WHOIS tool, and DomainTools is now the alternate tool because CAPTCHAs are annoying.  Resolves #456.
In addition, this commit adds another IP check tool in addition to the exiting Project Honeypot button, the Storm Forum Spam website.  Resolves #457.
Tested to work as expected on the ACC sandbox.
=> Swap WHOIS tools, add button to check IP with Stop Forum Spam

includes/DataObjects/User.php, includes/statistics/StatsInactiveUsers.php, templates/statistics/inactiveusers.tpl
Also bump time to 90d.
I'm openly admitting that this is a horrible patch.
The way I'd like to do this would be to do all the checking in the database, and pull out approval date, last active, username, etc in one query that did everything necessary. However, the code at present relies on PHP logic to get the current on-wiki username, which can't be done in the database, and requires user objects be pulled back from the database, thus we can't add extra fields to it. As such, we're stuck with either rewriting the oauth code (which is what I did in newinternal), or doing horrible hacks like pulling the approval date for every returned user separately, in individual queries. This is how the existing code works.
My change admits that this is bad, and does nothing to fix it.
Instead, I add to …
=> Inactivity changes to hide recently-approved users

acc.php, config.inc.php, users.php
Currently, if a checkuser clears the "CC to mailing list" option (which the UI allows them to do), the message to the mailing list is still sent as the underlying check only checks the user is a tool admin.
This fixes that, and cleans up a couple of other things spotted too.
=> Fix CC-to-mailing-list option for checkusers

acc.php, includes/DataObject.php, includes/DataObjects/Ban.php, includes/DataObjects/Comment.php, includes/DataObjects/EmailTemplate.php, includes/DataObjects/GeoLocation.php, includes/DataObjects/InterfaceMessage.php, includes/DataObjects/RDnsCache.php, includes/DataObjects/Request.php, includes/DataObjects/User.php, includes/DataObjects/WelcomeTemplate.php
Using LIMIT is unsafe in a replication environment due to the nature of
how MySQL retrieves rows to process the update might mean it retrieves a
different set of rows on the master and the slave, causing them to drift
out of sync.
This change removes this clause from all update and delete statements,
and by a happy coincidence all of these are already using the table's
primary key in the WHERE clause, so this is functionally a no-op, and
operationally hides a whole bunch of warnings in the log.
=> Remove LIMIT clauses from write queries

INSTALLING.md, config.inc.php, sql/patches/patch18-encoding.sql
Currently, the database schema is storing `latin1`-encoded text in `utf8`-encoded columns. Under PHP5.6, this is read back as a byte stream and displayed to the end user correctly in UTF-8, so nothing **appears** to be wrong.
Under PHP7.x, the application is not doing any encoding back to UTF-8, but is instead displaying the "already UTF-8" text, which is actually encoded with `latin-1`, leading to the text being displayed with the wrong encoding.
This patch changes the database to be in `utf8mb4` encoding, and does a conversion of all existing text fields from `latin1` to `utf8mb4`. We also convert some `BLOB` fields into `TEXT` fields to ensure the correct encoding is applied.
This patch is necessary for the application to run on PHP7, and thus it is necessary for the application to …
=> Fix encoding issues on PHP7

redir.php
Since the tools.wmflabs.org/toolname/ -> toolname.toolforge.org/ change, ipcheck has been acting up. This should fix it.
=> Update redir.php -- ipcheck domain

composer.json, includes/DataObjects/User.php, includes/ExceptionHandler.php, includes/Pages/PageLog.php, includes/Pages/PageUserManagement.php, includes/Pages/PageXffDemo.php, includes/Pages/UserAuth/PageForgotPassword.php, includes/Router/RequestRouter.php, includes/Security/CredentialProviders/ScratchTokenCredentialProvider.php, includes/Security/RoleConfiguration.php, includes/Tasks/JsonApiPageBase.php, includes/Tasks/PagedInternalPageBase.php, includes/WebRequest.php, resources/scss/_common.scss, templates/navigation-menu.tpl, templates/view-request/ip-links.tpl, templates/view-request/ip-section.tpl, templates/view-request/main-with-data.tpl, templates/view-request/request-log.tpl, templates/view-request/request-private-data.tpl, templates/xffdemo.tpl
The first of several bumper bugfix bonanzas.
This is done commit-by-commit, so you can see the commit history for a change log.
There is one bit of new functionality, and it's the move of the XFF demo page into the tool itself. Essentially, it's replacing [this page](https://accounts-dev.wmflabs.org/other/xff.html) with [this one](https://accounts-dev.wmflabs.org/rc/internal.php/xffdemo). I've left it at public access, but there's no inbound links to it from public areas, which matches the existing page. I'm happy to reduce the access scope, but I see little point as it's all demo data. The most someone malicious could do would be to see what tools we use, which they could from GitHub anyway.
=> First Bumper Bugfix Bonanza 

.travis.yml, sql/test_db.sh
This commit fixes the Travis configuration by making the following changes:
- Upgrade the MariaDB version to 10.2
- Upgrades Runkit to use Runkit7.  Runkit7 is a fork of Runkit that adds support for PHP 7.  The package is labelled as "alpha" in pecl, so I have manually configured to use v.3.0.0 right now.  Once a stable version is published, we can drop the 3.0.0 designator.
A couple of notes:
- I commented out the IRC notifications.  They need to be re-enabled.  I only did this to not flood the -dev channel with extraneous notifications.
- We... also probably want to squash this commit.  You can see by my log why I recommend that.  
Looking forward, MariaDB v.10.4 changes mysql authentication.  One of the tasks we need to consider is upgrading our Travis config to use this new …
=> Fix travis configuration

includes/Pages/PageViewRequest.php, templates/login/otp.tpl, templates/mfa/enableYubikey.tpl
Change Open Symbol to an Omicron to prevent confusion (changed from empty box)
=> Fix OTP Field Behavior and Browser Title Handling

includes/Pages/RequestAction/PageDeferRequest.php, includes/Security/RoleConfiguration.php
* Fixes an issue where non-admins could open a not-recently-closed request
* Prevent non-admins from re-opening a request where the data has been purged.
=> Fix the restrictions surrounding request closure

Dockerfile, INSTALLING.md, docker-compose.yml, docker/database.sh, docker/entrypoint.sh, docker/index.php, sql/patches/patch25-migrationscript-placeholder.sql, sql/patches/patch30-force-identification.sql, sql/patches/patch31-darkmode.sql, sql/seed/user_data.sql
These changes have no effect on Production, partly because a) they've
already run, and b) they depend on the use of the default install seed
data.
Roughly speaking, these fixes are as follows:
* Update the default password to one that's actually able to log in
after the changes to minimum password complexity rules
* Force the default admin user to be marked as identified by default
* Force the default admin user to use an automatic skin, which is the
default at the moment
* Update the status of the default admin user to 'Active' - the change
is normally done in the MigrateToRoles.php script, but this is not run
when the database is installed from the base data.
I've also yanked the instructions from INSTALLING.md to sync git
submodules (we got rid of those), and removed the setting for …
=> Fix database migration scripts for development installations.

config.inc.php, includes/Fragments/RequestData.php, includes/Fragments/RequestListData.php, includes/Pages/PageViewRequest.php, includes/Pages/RequestAction/PageCustomClose.php, includes/RequestList.php, includes/SiteConfiguration.php, resources/scss/_common.scss, templates/mainpage/requesttable.tpl, templates/view-request/request-private-data.tpl
I've added this flag to the summary on the zoom page, and also as a small flag on the request table for when private data is shown on the table.
I've also taken the opportunity to slightly redesign the related requests flag. We no longer show this when the count is zero, and we also now include an icon to let it fit in slightly better.
On the view request page, this now looks like this (where there are no other requests from this IP address, but one from the email address):
On the request list page (in admin view):
I suspect the design choices here will change again when we look at #425, but I think this is iterates in the right direction.
This fixes #469
=> Flag uncommon email domains from list in config

includes/Pages/PageWelcomeTemplateManagement.php
Since the following code explicitly checks if `$template` is false, it is not always an instance of `WelcomeTemplate`
=> PageWelcomeTemplateManagement: Fix incorrect @var tags

includes/ConsoleTasks/OldRequestCleanupTask.php
The old version didn't take into account comments being left on requests either by a requester or by tool users.
This meant that these requests would sit and not be deleted by the script which runs every night to clean up non-confirmed requests. In addition, because these requests were marked as "Open", these requests wouldn't have private data cleared from them either.
Now we take the approach of deleting requester comments when there are no other constraints which would prevent a request deletion, and when there are constraints which prevent deletion, we instead mark the request as closed, and "stale" to prevent an email confirmation from succeeding. The number of requests this affects should be close to zero though, because it requires a tool admin to explicitly override the …
=> Fix cleanup of non-email-confirmed requests

includes/DataObjects/User.php, includes/SiteConfiguration.php, sql/patches/patch35-user-welcometemplate-datafix.sql
This was setting the default welcome template for new users to `0` instead of `null`. This is fixed, and a constraint has been added to prevent this in future.
=> Fix minor issue with welcome template defaults

includes/API/Actions/CountAction.php, includes/DataObjects/Request.php, includes/Pages/Statistics/StatsTopCreators.php, includes/Pages/Statistics/StatsUsers.php
This field hasn't been populated [since 2015](https://github.com/enwikipedia-acc/waca/commit/ef3a35df06033845e7287d5dd53bfe12c9236f33), but was still being read from. Any "created"-type close reasons created since then will have been reporting incorrectly - thankfully that list is zero in production.
=> Fix usage of deprecated database field `emailtemplate.oncreated`

includes/Pages/PageWelcomeTemplateManagement.php
Alter the HTML retrieved from the `parse` api endpoint to convert relative links to absolute links
Closes #638
=> PageWelcomeTemplateManagement: link to enwiki in templates

includes/DataObject.php
Initially set to null, and explicitly checked against null in ::delete()
=> DataObject: document that $id can be null

includes/API/Actions/CountAction.php
For the log actions where a single action value corresponds to a single user attribute, use a loop to retrieve and set the user attributes.
=> CountAction: reduce code duplication with a loop

includes/Security/CredentialProviders/PasswordCredentialProvider.php, templates/forgot-password/reset-mail.tpl
This will revoke when the user logs in with their existing password, thus proving that they know their password and do not require a reset.
Fixes #648
=> Revoke password reset tokens on login

includes/Background/CreationTaskBase.php, includes/Pages/PageJobQueue.php, includes/Pages/RequestAction/PageCloseRequest.php, includes/Pages/RequestAction/PageCreateRequest.php, includes/Pages/RequestAction/PageCustomClose.php, templates/custom-close.tpl, templates/email-management/edit.tpl, templates/jobqueue/view.tpl, templates/logs/datatable.tpl
* Add new creation-type options to custom close for oauth/bot auto-creations
* Allows creation tasks to bypass email-sent checks if the creation task originates from a custom close
* Allow passing the email body to the creation task as a job parameter instead of passing an email template
* Mark auto-creations as having had an email sent
* Log custom closure text with the request
* Show the email body on the jobqueue entry in case of job failure
Fixes #677
=> Support auto-creation for custom closes

config.inc.php, includes/Background/BackgroundTaskBase.php, includes/Background/CreationTaskBase.php, includes/Background/Task/WelcomeUserTask.php, includes/ConsoleTasks/RunJobQueueTask.php, includes/DataObjects/JobQueue.php, includes/Helpers/IrcNotificationHelper.php, includes/Helpers/LogHelper.php, includes/Helpers/Logger.php, includes/Pages/PageJobQueue.php, includes/Pages/PageViewRequest.php, includes/Pages/RequestAction/PageCloseRequest.php, includes/Pages/RequestAction/PageCustomClose.php, includes/Pages/RequestAction/PageDeferRequest.php, includes/Pages/Statistics/StatsFastCloses.php, includes/Router/RequestRouter.php, includes/Security/RoleConfiguration.php, includes/SiteConfiguration.php, team.json, templates/custom-close.tpl, templates/jobqueue/view.tpl, templates/view-request/createbuttons/auto.tpl, templates/view-request/main.tpl, templates/view-request/request-status-buttons.tpl
* Fix invalid JSON introduced in 2449edd69
* Extend checks in the fast closes statistics page to check for enqueue times as well as closure times
* Add JS confirmation popup to auto-create buttons
* Automatically acknowledge failed auto-creation tasks. Requests are automatically deferred to the hospital queue anyway; requiring acknowledgement is unnecessary work.
* Stage jobqueue tasks before they can be run. This is to guarantee users time to cancel a mistaken auto-creation before it actually executes.
* Extract job queue batch size to a configuration option
* Add IRC ping for failed auto-welcome jobs
* Allow cancelling of jobqueue jobs independently. This *will not* move a request out of the jobqueue queue; if there are no creation jobs remaining, then the request will sit in that queue …
=> More autocreation bugfixes and missed functionality

includes/Security/RoleConfiguration.php
No need for a database migration to remove the role, the tool already allows removal of unrecognised roles from the UI.
=> Grant OAuth creation rights to all users

includes/DataObjects/Domain.php, includes/DataObjects/EmailTemplate.php, includes/Fragments/NavigationMenuAccessControl.php, includes/Fragments/TemplateOutput.php, includes/Helpers/LogHelper.php, includes/Helpers/Logger.php, includes/Pages/PageDomainManagement.php, includes/Pages/PageViewRequest.php, includes/Router/RequestRouter.php, includes/Security/RoleConfiguration.php, resources/scss/_common.scss, templates/domain-management/edit.tpl, templates/domain-management/main.tpl, templates/navigation-menu.tpl
As of this pull request, it does almost nothing other than look pretty, with the exception of managing the default close template for requests.
ACLs for this one are slightly complex.
* Tool users can see a simplified set of the configuration for all domains
* Tool admins can see all the configuration for their current domain, plus a simplified set of the configuration for all other domains. Tool admins can also change basic settings (name, default close template, default language) for their current domain.
* Tool roots can create domains and change anything.
As an example from a tool admin for enwiki perspective:
The next PR in this series will actually use a lot more configuration which is defined in this window.
Fixes #591
=> Basic domain management UI

redir.php, templates/view-request/ip-links.tpl
Adds a link to my Bullseye tool (used by a lot of CUs and proxy checkers already for IP info). I haven't gotten a test environment set up yet, so would appreciate if someone could double-check this, but it's a straight-up copy of existing code.
=> Add bullseye link to IP info

config.inc.php, includes/ApplicationBase.php, includes/Background/Task/BotCreationTask.php, includes/Fragments/TemplateOutput.php, includes/Helpers/BlacklistHelper.php, includes/Helpers/BotMediaWikiClient.php, includes/Helpers/EmailHelper.php, includes/Helpers/Interfaces/IEmailHelper.php, includes/Helpers/IrcNotificationHelper.php, includes/Helpers/OAuthProtocolHelper.php, includes/Helpers/RequestEmailHelper.php, includes/Pages/PageUserManagement.php, includes/Pages/PageViewRequest.php, includes/Pages/Request/PageRequestAccount.php, includes/Pages/RequestAction/PageCloseRequest.php, includes/Pages/Statistics/StatsUsers.php, includes/Pages/UserAuth/PageForgotPassword.php, includes/Pages/UserAuth/PagePreferences.php, includes/Providers/CachedApiAntispoofProvider.php, includes/SiteConfiguration.php, includes/Validation/RequestValidationHelper.php, includes/WebStart.php, templates/offline/external.tpl, templates/offline/internal.tpl, templates/request/request-form.tpl, tests/includes/Helpers/EmailHelperTest.php, tests/includes/SiteConfigurationTest.php, tests/includes/Validation/RequestValidationHelperTest.php
This moves some of the configuration settings from `config.inc.php` into the interface itself.
The UI for these settings already exists - it's the "Domain Management" page. This simply moves all the usages over.
At the moment, there's a lot of "FIXME: Domains!" in the code - this is intentional as this will be sorted in a later pull request. At the moment, we're only interested in pulling the settings from the default domain, ID 1. Enabling full usage of domain settings will come later.
=> Start using the settings from Domain Management

includes/Exceptions/AccessDeniedException.php, includes/Exceptions/NotIdentifiedException.php, includes/Fragments/NavigationMenuAccessControl.php, includes/Pages/PageBan.php, includes/Pages/PageDomainManagement.php, includes/Pages/PageEditComment.php, includes/Pages/PageFlagComment.php, includes/Pages/Registration/PageRegisterBase.php, includes/Pages/RequestAction/PageBreakReservation.php, includes/Pages/RequestAction/PageCreateRequest.php, includes/Pages/RequestAction/PageCustomClose.php, includes/Pages/UserAuth/PageOAuth.php, includes/Security/DomainAccessManager.php, includes/Tasks/InternalPageBase.php, includes/WebStart.php
This was caused by a dependency on DomainAccessManager, which wasn't passed in where it needed to be.
Fixed in two ways - a) passing it in where it needs to be, and b) making it fail more gracefully when it's not passed in (just in case this happens again in the future)
=> Fix breakage of access denied errors and non-identified errors

includes/API/Actions/JsTemplateConfirmsAction.php, includes/API/Actions/JsUsersAction.php
TaskBase::getDatabase() has no side effects, and the results is unused, so there is no need to call the method.
=> API actions: remove unused code

includes/ConsoleTasks/RegenerateStylesheetsTask.php
scssPhp has deprecated the use of 'ScssPhp\\ScssPhp\\Formatter\\Compressed' and also ->comple. Replaced them with the newer versions
=> Replace Deprecated code

includes/Fragments/NavigationMenuAccessControl.php, includes/Fragments/TemplateOutput.php, includes/Tasks/InternalPageBase.php, templates/navigation-menu.tpl
These badges are for the flagged comments and the job queue.  For flagged comments, any comments that have a flag are counted.  For the job queue, any failed and not acknowledged error is counted.  If we have either, it also shows a badge on the main navigation item to draw attention.
#735
This is a preview of what they look like, for admins and regular users.  
Note that as of right now, everyone has access to the job queue.  So, the badge will show for all users.  If we want to limit that, we can.
=> Add badges to highlight concern areas

includes/DataObjects/Domain.php, includes/Pages/PageDomainManagement.php, includes/Pages/Registration/PageRegisterBase.php, includes/Pages/Registration/PageRegisterOption.php, includes/Pages/UserAuth/Login/LoginCredentialPageBase.php, includes/Pages/UserAuth/PageOAuthCallback.php, includes/Security/DomainAccessManager.php, includes/SiteConfiguration.php, sql/patches/patch40-userdomains.sql, templates/domain-management/edit.tpl, templates/domain-management/main.tpl, templates/navigation-menu.tpl, templates/registration/option.tpl, templates/registration/register.tpl
This PR does four things:
* Adds all existing users to all existing domains. In practice, this means just enwiki, since enwiki is the only domain which exists (in production)
* Defines the current Guide URL to be per-domain
* Allows a user to choose the domain they want access to when they sign up
* Sets the current domain to a domain the user is in on login.
=> Assign users to domains

includes/Pages/PageQueueManagement.php
API name was never set, but the regex for it was also broken.
=> Fix queue creation

includes/ConsoleTasks/ClearOAuthDataTask.php, includes/Helpers/SearchHelpers/SearchHelperBase.php
Currently, SearchHelpers will do nothing if you pass an empty list to their SQL `IN(...)` clause generation tools. This means that the IN() is never added to the query, and it's as if you'd never specified that you wanted an `IN(...)` clause at all.
This is not expected, as I'd anticipate that specifying an `IN(...)` clause and passing an empty array would indicate you expect zero results (nothing selected to return). Indeed, several usages of this function are built in this way - for example, pull all usernames for users who reserved this set of requests, but it's an empty set to retrieve *all* usernames.
We also fix one such usage which only passes the *first* result into an `IN(...)` clause, instead of all discovered results.
This issue was spotted in the MariaDB slow query log running …
=> Fix SearchHelper IN() clause construction

Dockerfile, docker-compose.yml, docker/config.local.inc.php, docker/entrypoint.sh, docker/msmtprc, docker/rabbitmq-definitions.json, docker/rabbitmq.conf, team.json
Various improvements to the Docker setup for local development:
- Adds a default config.local.inc.php that will be added to the root dir if you don't already have one; should work out of the box for any Docker setup
- Adds a RabbitMQ definitions file which creates a "main" exchange and queue (also specified by default in the Docker config.local.inc.php file) that receives all notifications sent by the tool. Uses a fanout exchange so that all notifications are delivered to the same "main" queue regardless of routing key.
- Adds a mailsink service to the docker-compose environment and configures the application service to use it; this allows for easy local testing of email-based functionality.
Secondarily:
- Disable XDebug's `discover_client_host` setting as this was causing more issues …
=> Various Docker improvements

.travis.yml, Dockerfile, INSTALLING.md, docker-compose.yml
NOTE: this migration has already happened in Production, so this is just an update to CI/Docker/documentation.
=> Bump PHP/MariaDB versions to reflect production migration

docker/rabbitmq-definitions.json, docker/rabbitmq.conf
Updates RabbitMQ Docker config/definitions to reflect the change from 3.10 to 3.8 in PR #766.
This PR (the one you're currently reading) is only required if keeping the change from 3.10 to 3.8 in PR #766; if RabbitMQ is held at 3.10, this PR is unnecessary and should be closed.
Tested locally to function as expected by creating a request, email confirming that request (using the Docker mailsink), and reserving the request through the internal interface and verifying that notifications were sent to RabbitMQ as expected.
=> Update RabbitMQ Docker config for 3.10 -> 3.8

INSTALLING.md, docker/README.md
Since I've done a lot of work to support Docker-based ACC setups, making it "officially supported" by writing up a proper Docker README with all the information one might need to get started with it.
=> Create Docker docs

config.inc.php, includes/IdentificationVerifier.php, includes/SiteConfiguration.php
This patch makes the location of the ID noticeboard lookups fully configurable, in case the move to foundationwiki goes ahead.
=> Extract ID noticeboard wiki to variable, and add to config.inc.php

docker-compose.yml, docker/README.md, docker/rabbitmq-definitions.json
In preparation for upgrading the ACC appserver to the latest Debian, bumps RabbitMQ from 3.8 to 3.10.8 in `docker-compose.yml`, which is the version currently available in the package repos for Debian bookworm as of this PR. (See https://packages.debian.org/stable/rabbitmq-server)
Also updates the Docker README to reflect version bumps to MariaDB and RabbitMQ.
Tested locally by wiping out everything (`docker system prune -af --volumes && docker volume prune -af`) and rebuilding from scratch (`docker compose up --detach`), then making a request, email confirming it via the mailsink, confirming that RabbitMQ shows the IRC notification, and then logging into the interface to confirm the presence of the request.
For future reference: RabbitMQ 3.10.8 accepted the 3.8 …
=> Docker: Bump RabbitMQ 3.8 -> 3.10.8, update docs

.github/workflows/ci.yml, Dockerfile, docker-compose.yml, docker/README.md, docker/database.sh
Makes the following updates to the Docker configuration:
- Updates Debian to bookworm
- Updates PHP to version 8.2
- Updates the database seed script for the new test_db.sh parameters
In addition, adds some notes to the Docker README for what to do if you run into font-awesome installation issues (which I did a couple of times).
Also adds a step to the GitHub Actions CI to wait for MariaDB to become available before continuing, as opposed to a somewhat-unreliable `sleep 5`.
Resolves #827.
- Blew away local Docker and ran `docker compose up` from scratch as-committed (i.e., with the `composer-vendor` workaround commented out)
- Confirmed that database seeds correctly
- Confirmed that `package-lock.json` no longer gets changed
- Confirmed that able to submit new requests and log in to ACC
- …
=> Docker updates: Debian bookworm, PHP 8.2, and DB, plus MariaDB improvement in CI

.github/workflows/ci.yml
This isn't exactly secret, and the instance is only used to test the DB scripts so it's not important in any way. This also lets PRs from others (eg dependabot) run the DB CI job.
Also set a timeout for the wait job so it can't run forever
=> Don't use secrets for the CI MariaDB server

includes/Pages/PageEditComment.php
Fixes call to `Logger::unflaggedComment(...)` introduced in [023e464c](https://github.com/enwikipedia-acc/waca/commit/023e464c869b18b3d6dae62f84b5ef00c025b2f9#diff-ab0b1a2e5ce308825251eca14f41898aaff27d5a431ba8237342419108c59f1aL331-L336)
=> Fix missing parameter on function call

includes/Pages/UserAuth/MultiFactor/PageMultiFactor.php, templates/mfa/disableOtp.tpl, templates/mfa/enableYubikey.tpl, templates/preferences/changePassword.tpl, templates/registration/register.tpl
* Clarifies that authentication prompts surrounding enabling/disabling MFA ask for your tool password
* Change the styling of the password change page to better match other auth-type pages
* Add big notices to registration and password change reminding people to not use their WM passwords
=> In-tool documentation tweaks about passwords

includes/Helpers/PreferenceManager.php, includes/Pages/PageMain.php, includes/Pages/UserAuth/PagePreferences.php, templates/mainpage/accordiongroup.tpl, templates/preferences/prefs.tpl
Resolve #566 .
Add a preferences option to show/hide queue help text. Defaulting to on/show
=> Make queue help messages dismissable

templates/view-request/username-section.tpl
Resolves #494 
Allow the user to select search options on their Wikipedia account rather than enforcing it via the tool
=> Change Wikipedia Link

README.md
Travis is no longer in use for CI
=> Replace Travis CI with GitHub Actions Badge

includes/ConsoleTasks/ClearOldDataTask.php, includes/Helpers/IrcNotificationHelper.php, includes/Helpers/LogHelper.php, includes/Pages/PageEditComment.php, includes/Pages/PageFlagComment.php, includes/Pages/PageListFlaggedComments.php, includes/Pages/PageViewRequest.php, resources/scss/_viewRequest.scss, resources/scss/bootstrap-alt.scss, templates/edit-comment.tpl, templates/flagged-comments.tpl, templates/view-request/request-log.tpl
* Show request status on edit comment
* Show a warning when editing a flagged comment on a non-closed request
* Show link to edit comment and the comment in-situ on the request from the log page.
* Fix issue where it was impossible to only unflag a comment via the edit comment screen
* Edit comment screen now returns you to either the view request page or the flagged comments page, depending on which you used to edit the comment.
* Hides flagged comments from view when request is unreserved (#777)
* Handles some extra edge cases for when a user has access to the edit interfaces, but doesn't have `RequestData::alwaysSeePrivateData`
* Adds an IRC ping for outstanding flagged comments (#777)
=> Edit comment QoL tweaks

.github/workflows/ci.yml, includes/DataObjects/Ban.php, includes/DataObjects/Log.php, includes/Helpers/BanHelper.php, includes/Helpers/LogHelper.php, includes/Helpers/Logger.php, includes/Pages/PageBan.php, includes/Router/RequestRouter.php, includes/Security/RoleConfiguration.php, includes/SiteConfiguration.php, resources/global.js, sql/patches/patch48-globalbans.sql, templates/bans/banform.tpl, templates/bans/list.tpl
Implements global bans and ban editing
=> Global bans and ban editing

includes/DataObjects/UserRole.php, includes/Helpers/LogHelper.php, includes/Helpers/Logger.php, includes/Pages/PageUserManagement.php, includes/Pages/Statistics/StatsUsers.php, includes/Security/RoleConfiguration.php, includes/Security/SecurityManager.php, includes/SiteConfiguration.php, sql/patches/patch49-globalroles.sql, sql/test_db.sh, templates/usermanagement/roleedit.tpl
Roles can now be either defined as a "local" role (like tool admin or checkuser), or a "global" role (like tool root or steward).
Global roles automatically apply across all domains. Local roles only apply in the domain in which they are granted.
There is no practical difference between how a global and a local role are treated - the only difference occurs when the role is granted. If it's defined as global in RoleConfiguration, the application will ensure it is saved as a global role instead of a local role. From a data storage point of view, a global role grant simply has the `userrole.domain` column set to null.
This means it is possible to live-hack local roles to apply as global roles or vice-versa by directly manipulating the database and it'd behave as you'd otherwise expect. …
=> Implement global roles

includes/Pages/Statistics/StatsMain.php
Statistics for "Tool administrators" and "Tool users" are broken right now on prod. I think this fixes them. (But I couldn't get the docker to work in order to test this, so please make sure this doesn't break anything!)
=> Fix broken statistics

.github/workflows/ci.yml, includes/Fragments/PrivacyStatement.php, includes/Helpers/MarkdownRenderingHelper.php, includes/Pages/PagePrivacy.php, includes/Pages/PagePublicPrivacy.php, includes/Router/PublicRequestRouter.php, includes/Router/RequestRouter.php, includes/Security/RoleConfiguration.php, includes/SiteConfiguration.php, package.json, resources/scss/_common.scss, resources/scss/_footer.scss, resources/scss/_markdown.scss, resources/scss/public.scss, templates/base.tpl, templates/form-management/preview.tpl, templates/markdown/private.tpl, templates/markdown/public.tpl, templates/publicbase.tpl, templates/registration/register.tpl, templates/request/legal-info.tpl, templates/request/request-form-dynamic.tpl, templates/request/request-form.tpl
This adds links to the WMCS TOS and our brand new {entry}.php/privacy pages, which render the privacy statement in the correct context from a markdown file. Links have been added to both public and private footers, and to relevant data submission forms (request and register) for when users start using the service.
I've also taken the opportunity to sassify the public stylesheet.
=> Add privacy statement to relevant places

includes/Helpers/IrcNotificationHelper.php
Resolves #957.
Notes:
* I tested this with the Docker config's default RabbitMQ settings (which do not include SSL/TLS), and RabbitMQ received the messages correctly. I could not test with SSL/TLS because I'm running the tool on my local machine.
* I got multiple exceptions/errors when setting up, logging in, creating a request, and reserving that request:
* `WARN[0000] /home/m/waca/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion`
* `( ! ) Warning: Undefined array key "hidden" in /var/www/html/templates_c/d5b8cd18de789ef98bed0c224d77de2b5c511f8b_0.file.request-log.tpl.php on line 48` in the comments section after reserving the request.
* `( ! ) Deprecated: Using unregistered function "count" in a template is …
=> Amqp deprecation fix

includes/ConsoleTasks/AutoFlagCommentsTask.php, maintenance/AutoFlagComments.php
This hopefully should close the gap slightly between what humans forget to flag and what we really should be flagging.
This is automated, and probably misses a lot. It's a copy-paste of the query I've been using manually, so there's still a lot of things commented out as they'll throw far too many false positives.
I fully expect this query to evolve over time.
=> Add automatic comment flagging script

templates/exception/account-declined.tpl, templates/exception/account-suspended.tpl, templates/logs/datatable.tpl
This appears to only be triggerable from user input by tool admins, so the risk factor is low and it's trivially auditable if anyone takes advantage.
=> Fix XSS in log comments

includes/IIdentificationVerifier.php, includes/IdentificationVerifier.php
Currently, if a user's on-wiki username is not set, because they haven't completed the required OAuth verification as part of the registration process, for example, it's not possible to view the user's information/statistics page because `isUserIdentified()` can't handle `null`s. This addresses the issue; if passing in `null` or an empty string, it now always returns `false`, and `null`s are allowed by the type check.
Tested locally to resolve the issue as expected.
=> Handle nulls in isUserIdentified

.github/dependabot.yml
Assignees are broken, and reviewers are going away soon per the GitHub changelog.
=> Remove reviewers/assignees from dependabot.yml
